services:
  allwaysui:
    image: entrius/aw-ui:latest
    mem_limit: '512mb'
    container_name: aw-ui
    restart: always
    ports:
      - '127.0.0.1:9080:9080'
    networks:
      - allways_network
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'

  watchtower:
    image: nickfedor/watchtower
    container_name: aw-ui-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_POLL_INTERVAL: 150
      WATCHTOWER_LABEL_ENABLE: 'true'
      WATCHTOWER_CLEANUP: 'true'

networks:
  allways_network:
    external: true
